# -*- coding: utf-8 -*-
"""hotel booking analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BXoIbLKW0Prj3jZfnpyvVjN6hkjYlfe2

# **HOTEL BOOKING ANALYSIS**



---

name=**ABHISEKH KUMAR THAKUR**

team type=**INDIVIDUAL**

This is a project on hotel booking analysis.I have tried to get general insights from the data using various cleaning and treatments of outliers .
I have tried to find patterns and average sense of demands in hotel types and customers preferences in hotel industry based on the given data.This project is basically a simple EDA which will help any stakeholder to understand the data.
And most importantly ,I have tried to analyse only booking part using various exploratory data analysis methods.

***Importing data***
"""

#mounting google drive
from google.colab import drive
drive.mount('/content/drive')



# Commented out IPython magic to ensure Python compatibility.
#importing necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
import numpy as np

#loading the dataset hotel bookings to df
path='/content/drive/MyDrive/csvfiles/Hotel Bookings.csv'
df=pd.read_csv(path)

df.head().T

"""***Cleaning data***

"""

# for checking if there is any null values
df.isnull().sum().sort_values(ascending=False)

df.info()

"""Some columns have null values which should be treated before further analysis.

Treating outliers
"""

#for children
df['children'].median()

df['children'].mode()

round(df['children'].mean())

df['children'].unique()

df[df['children'].isna()]

#we will replace the null values with median for children
df['children'].fillna(df['children'].median(),inplace=True)

df[df['children'].isna()]

"""after filling values, children column no longer have any null values"""

#for country column
df.isnull().sum()

#for country
df[df['country'].isna()].head()

#we will replace the null values of country with the most frequent observation
df['country'].mode()[0]

"""Country column have PRT as most repeated which can be used to fill null values in country column"""

df['country'].fillna(df['country'].mode()[0],inplace=True)

df.isnull().sum()

"""Agent and company columns have high number of null values and also are not of much importance in hotel booking, so we will drop these including some more"""

df.columns

df_new=df.copy()

df_new.info()

#Dropping unnecesary columns which will be not used for further analysis here
df_new.drop(['arrival_date_week_number','arrival_date_day_of_month','agent','company','previous_cancellations','previous_bookings_not_canceled'],axis=1,inplace=True)

df_new.isnull().sum()

"""Data has been cleaned for further EDA"""

df_new.head()

# Now we will explore our data through various visualizations and try to remove outliers

#Lets take a quick visual of our data
df_new.hist(figsize=(16,16))
plt.show

df_new.columns

df_new.info()

#for outliers
plt.figure(figsize=(35,10))
sns.boxplot(data=df_new[['lead_time','stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children', 'babies', 'booking_changes', 'days_in_waiting_list', 'adr', 'required_car_parking_spaces', 'total_of_special_requests']])
plt.show

#all columns looks good except for 'lead time','days in waiting list' and 'adr'
sns.boxplot(data=df_new['lead_time'])
plt.title('lead time')

sns.boxplot(data=df_new['adr'])
plt.title('adr')

"""Removing outliers

"""

#for lead time
df_new.hist('lead_time')



sns.boxplot(data=df_new['lead_time'])

df_new['lead_time'].describe()

q1=df_new['lead_time'].quantile(0.25)
q3=df_new['lead_time'].quantile(0.75)
median=df_new['lead_time'].quantile(0.5)
iqr=q3-q1
lower=q1-1.5*iqr
upper=q3+1.5*iqr
print(lower,upper,median)

df_new.describe()

(df_new['lead_time']>upper).value_counts()

#For lead time, we will consider only those values which are under the upper cap
df_new=df_new[df_new['lead_time']< upper]

#for adr, only one value is a outliers which we will treat
sns.boxplot(data=df_new['adr'])

df_new[df_new['adr']> 5000]

#removing outlier in adr column
df_new=df_new[df_new['adr']< 5000]

df_new.describe()

"""Analysis using some visualization

**Question**
What is the most preferred category for hotel booking?
"""

#for hotel type
df_new['hotel'].value_counts().plot.pie(explode=[0.05, 0.05], autopct='%1.1f%%', shadow=True, figsize=(6,6),fontsize=20)
plt.title('hotel category')

"""**Answer**

Most bookings are coming for city hotels (66% approximately), while only 34 percent approximately of the bookings are from resort hotel.
"""

#for cancellation analysis, first we will replace the value with more interpretable one like for 0 and 1 in is_canceled
#we will replace with not canceled and cancelled repectively
df_new['is_canceled'] = df_new['is_canceled'].replace([0,1], ['not canceled', 'is canceled'])

"""**Question**

Of the total bookings , how much of the booking have been cancelled?
"""

df_new['is_canceled'].value_counts().plot.pie(explode=[0.05, 0.05], autopct='%1.1f%%', shadow=True, figsize=(6,6),fontsize=20)
plt.title("Cancellation and non Cancellation")

"""**Answer**

Approximately 36 percent of hotel bookings have been cancelled (including both resort and city hotel)
"""

#Bifurcation of cancellation along both type of hotel
df_new.groupby("hotel")['is_canceled'].value_counts()

#for lead time impact

"""**Question**
What is the avg lead time for both type of hotel?
"""

#Visualizing lead time for both category
sns.histplot(x=df_new['lead_time'],hue= df_new['hotel'] ,multiple='dodge')

"""**Answer**

City hotel seems to have high lead time than resort hotel.
lead_time for both type of hotel seems to lie in the range of 0 to 50 days.

**Question**

What is the avg number of bookings  in days in any week and weekend?
"""

#for week and weekend nights stays.
# we will use countplot on weekd stays

plt.rcParams["figure.figsize"]=[10,4]
plt.rcParams["figure.autolayout"]=True
f,axes=plt.subplots(1,2)
sns.countplot(x=df_new['stays_in_week_nights'],hue= df_new['hotel'],ax=axes[0])
sns.countplot(x=df_new['stays_in_weekend_nights'],hue= df_new['hotel'],ax=axes[1])

plt.show()

"""**Answer**

As we already know the bookings for resort hotel is relatively low so weekwise bookings also less for resort hotel.
For city hotel, weekend night count is low as compared to other days.
Customers generally book for 2  days followed by 1 day booking

**Question**

What is the number of adults who come for booking in groups or individually?
"""

#2 has been appeared the most for adults booking
df_new['adults'].value_counts().sort_values(ascending=False)

sns.countplot(x=df_new['adults'],hue=df_new['hotel'])

"""**Answer**

Most of the bookings are for 2 adults.

**Question**

What is the most preferred meal type over hotels?
"""

df_new['meal'].value_counts().plot.pie(autopct='%1.1f%%', shadow=True, figsize=(7,9),fontsize=20)
plt.title("meal preferred")

sns.countplot(x=df_new['meal'],hue=df_new['hotel'])

"""**Answer**

77 percent of the customers preferred breakfast at bed.
Customers likes Half board meal more in resort hotels.

**Question**

From which country , bookings are comings the most?
"""

#for country
df_new['country'].value_counts().head(10).plot(kind='pie')

df_new['country'].value_counts(normalize=True)*100

"""**Answer**

40 percent of the bookings are from portugal, followed by great britain and then france.

**Question**
From which medium hotels are mostly booked?
"""

# for booking medium , we will choose market segment
df_new['market_segment'].value_counts()

sns.countplot(x=df_new['market_segment'],hue=df_new['hotel'])

"""**Answer**

Online booking method is most preferred.
"""

# for distribution channels summary
df_new['distribution_channel'].value_counts()

"""**Question**
What can we say about repeated guest , whether they rebook or not?
"""

df_new['is_repeated_guest'].value_counts(normalize=True)*100

sns.countplot(x=df_new['is_repeated_guest'],hue=df_new['hotel'])

"""**Answer**

96 percent of the customers are new which means they dont book the previous hotels in general.

**Question**

For which room types , bookings are coming the most?
"""

df_new['reserved_room_type'].value_counts()

sns.countplot(x=df_new['reserved_room_type'],hue=df_new['hotel'])

"""**Answer**

A type room has been preferred the most over others in both type of hotel
"""

(df_new['reserved_room_type']==df_new['assigned_room_type']).value_counts(normalize=True)

"""**Also**
87 percent of the time room has been assigned as the reserved. and in rest times room type has been alloted as desired.
"""

df_new.info()

"""**Question**

 What is the percentage of total customers who change their bookings?
"""

df_new['booking_changes'].value_counts(normalize=True)*100

"""**Answer**

Only 16% is the chance of change in booking which is not that much significant.

**Question**
What is the mode of payment through which customers make payments?
"""

#for payment method we will see deposit_type
df_new['deposit_type'].value_counts().plot(kind='pie',autopct='%1.1f%%')

"""**Answer**

Major chunk of customers prefer on-site payment methods .

**Question**
In which month bookings have been done the most?
"""

#finding the month in which most number of bookings have been done
df_new['arrival_date_month'].value_counts().plot(kind='bar')

sns.countplot(y=df_new['arrival_date_month'])
plt.title('monthwise booking')
plt.ylabel('Month')
plt.xlabel('Customers')

"""**Answer**

Most of the bookings are done in August

**Question**
Which type of customers generally do hotel bookings?
"""

#we will use pie chart for customer type segments
df_new['customer_type'].value_counts().plot(kind='pie',explode=[0.2,0.11,0.11,0.11],)

"""**Answer**

Mostly hotels are booked by transient customers

**Question**
What can we say about average daily rate?
"""

#Interpreting adr columns for getting avarage daily rate insight
df_new.groupby('arrival_date_month')['adr'].mean().plot(kind='bar')

"""**Answer**

Average daily rate is highest for the month of august and

also we have already concluded that august has the highest number of bookings.

# **Conclusions and recomendations **


*   Customers are more for city type of hotel so City hotels should increase their availabilities.

*   There is 36 percent cancellations which is significant so hotels can provide some optional voucher instead of cancelling so that customers can be attracted and retained.

*  The demand for hotels in august month is most and adr is also highest for august month, so hotels should run promotional schemes for august month to attract customers.

* BB type of meal has been opted the most so, hotels can mak this complimentary so that customers can be retained.
* Customers make online bookings , so hotels should be listed online for easy bookings.
* Most customers make their payments at hotels, so hotels should provide online discounts for more digital.
* Transient customers are significantly very high so hotels should provide schemes for first timers to book intantly and get rewards.
* Repeated customers are very low, so hotels should provide better hospitality and services to retain their customers.
"""